/* 
 * ===========================================================================
 * File Name BaseAppConstants.java
 * 
 * Created on Oct 11, 2016
 *
 * This code contains copyright information which is the proprietary property
 * of ArtigemRS-FI. No part of this code may be reproduced, stored or transmitted
 * in any form without the prior written permission of ArtigemRS-FI.
 *
 * Copyright (C) ArtigemRS-FI. 2016
 * All rights reserved.
 *
 * Modification history:
 * $Log: BaseAppConstants.java,v $
 * ===========================================================================
 */

package com.nextgen.enums;

/**
 * Enum for used in application
 * 
 * @author vikashk3 - Chetu
 * @version 1.0 - Oct 11, 2016
 */

public enum BaseAppConstants {
	
	ACCEPT("Accept"),
	ACCESS_CONTROL_ALLOW_CREDENTIALS("Access-Control-Allow-Credentials"),
	ACCESS_CONTROL_ALLOW_HEADERS("Access-Control-Allow-Headers"),
	ACCESS_CONTROL_ALLOW_METHODS("Access-Control-Allow-Methods"),
	ACCESS_CONTROL_ALLOW_ORIGIN("Access-Control-Allow-Origin"),
	ACCESS_CONTROL_EXPOSE_HEADERS("Access-Control-Expose-Headers"),
	ACCESS_CONTROL_MAX_AGE("Access-Control-Max-Age"),
	ACCESS_CONTROL_REQUEST_HEADERS("Access-Control-Request-Headers"),
	ACCESS_CONTROL_REQUEST_METHODS("Access-Control-Request-Methods"),
	ADDRESS("Address"),
	ADDRESS_COMPONENTS("address_components"),
	ADJUSTER("ADJUSTER"),
	ADMIN("ADMIN"),
	AES("AES"),
	ALL("ALL"),
	ALL_ITEMS("ALL ITEMS"),
	ANCHOR_INDEX("#index"),
	APPLICATION_JSON("application/json"),
	APPRAISED("APPRAISED"),
	APPROVED("APPROVED"),
	ART_BASE_MATERIAL("artbasematerial"),
	ART_FRAME_MATERIAL("artframematerial"),
	ART_FRANE_STYLE("artframestyle"),
	ART_MATTING("artmatting"),
	ART_MEDIA_MATERIAL("artmediamaterial"),
	ART_POTTERY_TREATMENT("artpotterytreatment"),
	ART_PROTECTIVE_OVER("artprotectiveover"),
	ART_SCULPTURE_STAND_MATERIAL("artsculpturestandmaterial"),
	ART_SCULPTURE_TECHNIQUE("artsculpturetechnique"),
	ART_SUBJECT("artsubject"),
	ARTIGEM_RS_MEDIA_FILES("artigemrs-mediafiles"),
	ARTIGEM_TEAM("Artigem Team"),
	ASSIGNED("ASSIGNED"),
	ATTRIBUTE("ATTRIBUTE"),
	AUDIENCE("audience"),
	AUTO("AUTO"),
	BACK_SLASH("/"),
	BLANK(""),
	BLANK_PAGE("This page will be followed by a blank page!"),
	CATALINA_BASE("catalina.base"),
	CATEGORY("CATEGORY : "),
	CATEGORY_LINK_TARGET("catLinkTarget"),
	CATEGORY_LINK_TARGET_REFERENCE("#catLinkTarget"),
	CATEGORY_WISE_SUMMARY("Category wise Summary"),
	CLAIM("CLAIM"),
	CLAIM_CENTER("Claim Center"),
	CLAIM_COMPLETED("Completed"),
	CLAIM_PROCESSING("Processing"),
	CLAIM_STATUS_DEFAULT("OPENED"),
	CLAIM_STATUS_SETTELED("SETTELED"),
	COLORED_STONE_EARRING("COLORED STONE EARRING"),
	COMMA(","),
	COMPANY("COMPANY"),
	CONTACT("CONTACT"),
	CORPORATE_USER("CORPORATE USER"),
	COST("Cost"),
	TOKEN_CREATED("created"),
	DAMAGED_ITEMS("DAMAGED ITEMS"),
	DD_MM_YYYY("dd/MM/yyyy"),
	DEFAULT("default"),
	DIAMOND_CLARITY("diamondclarity"),
	DIAMOND_COLOR_GRADES("diamondcolorgrades"),
	DIAMOND_CUT_GRADE("diamondcutgrade"),
	DIAMOND_GEMLAB("diamondgemlab"),
	DIAMOND_PENDENT("DIAMOND PENDENT"),
	DIAMOND_SHAPES("diamondshapes"),
	DIAMOND_SOLITARE("DIAMOND SOLITARE"),
	DOLLAR_SIGN("$"),
	DOT("."),
	DRAWINGS("DRAWINGS"),
	EMPTY_FILE("Empty File"),
	ENCRYPTION_KEY("1Hbfh667adfDEJ78"),
	EXPORT("EXPORT"),
	EXPORT_DATA("exportdata"),
	FALSE("FALSE"),
	FAX("FAX"),
	GEMSTONE_SHAPES("gemstoneshapes"),
	GEMSTONE_TYPES("gemstonetypes"),
	GEMSTONES_QUALITIES("gemstonesqualities"),
	GEOMETRY("geometry"),
	GET("GET"),
	GO_TO_INDEX("Go To Index"),
	GOOGLE("Google"),
	GUIDELINE("GUIDELINE"),
	HEX_CHAR("SHA1PRNG"),
	HOME("HOME"),
	IMAGE("IMAGE"),
	INDEX("index"),
	INDEX_CONSTANT("INDEX"),
	INDEX_REFERENCE("#index"),
	INSPECTION("INSPECTION"),
	INSTRUCTIONS("INSTRUCTIONS"),
	INVOICE("INVOICE"),
	INVOICE_STATUS_APPROVED("APPROVED"),
	INVOICE_STATUS_CREATED("CREATED"),
	INVOICE_STATUS_REJECTED("REJECTED"),
	INVOICE_STATUS_INPROGRESS("IN PROGRESS"),
	INVOICE_STATUS_SETTLED("SETTLED"),
	INVOICE_STATUS_REVIEW("UNDER REVIEW"),
	ITEM("ITEM"),
	ITEM_NAME("Item Name"),
	ITEM_STATUS_CREATED("CREATED"),
	ITEM_STATUS_ASSIGNED("ASSIGNED"),
	ITEM_STATUS_UNDERREVIEW("UNDER REVIEW"),
	ITEM_STATUS_APPROVED("APPROVED"),
	ITEM_STATUS_INSPECTION("INSPECTION"),
	ITEM_STATUS_UNDER_REPLACEMENT("UNDER REPLACEMENT"),
	ITEM_STATUS_UNDER_SETTLED("SETTLED"),
	LATITUDE("lat"),
	LOCATION("location"),
	LONG_NAME("long_name"),
	LONGITUDE("lng"),
	METALTYPES("metaltypes"),
	MOBILE("mobile"),
	NAME("Name"),
	NAME_STR("name"),
	NO_DATA("No Data"),
	NOT_AVAILABLE("N/A"),
	NOTE("NOTE"),
	NOTIFICATION("NOTIFICATION"),
	NUMBER_OF_ITEMS("Number of Items"),
	ONE("1"),
	OPENED("OPENED"),
	OS_NAME("os.name"),
	OS_WINDOW("win"),
	PAGE("PAGE"),
	PAGE_NUMBER("Page No."),
	PAINTING("PAINTING"),
	PDF("PDF"),
	PDF_EXTENSION(".pdf"),
	PDF_PAGE_FORMAT("1,%s, 3-%s, %s"),
	PENDING("PENDING"),
	PERSONAL("PERSONAL"),
	PIPE("|"),
	POETTRY_CERAMICS("POETTRY & CERAMICS"),
	POLICY_HOLDER_NAME("Policy Holder Name"),
	POST("POST"),
	POST_LOSS("POST_LOSS"),
	POST_LOSS_INVENTORY("Post-Loss-Inventory"),
	POST_LOSS_INVENTORY_FILE("PostLostInventoryFiles"),
	POST_LOSS_ITEMS("POSTLOSS ITEMS"),
	POSTLOSS("POSTLOSS"),
	PRINTS_POSTERS("PRINTS & POSTERS"),
	PRODUCT_NUMBER("Product No."),
	PROJECT_NAME("ArtigemRS-FI"),
	PURCHASE_DATE("Purchase Date"),
	PURPOSE("purpose"),
	QUANTITY("Quantity"),
	RATING("rating"),
	REJECTED("REJECTED"),
	REPLACED("REPLACED"),
	REPORT("REPORT"),
	RESULTS("results"),
	ROLE_CLAIM_CENTER_ADMIN("CLAIM CENTER ADMIN"),
	ROOM("Room"),
	ROOM_IMAGES_WITH_POST_LOSS_ITEMS("Room Images with post loss items"),
	ROOM_LINK_TARGET("roomLinkTarget"),
	ROOM_LINK_TARGET_REFERENCE("#roomLinkTarget"),
	ROOM_WISE_SUMMARY("ROOMWISE SUMMARY"),
	SCHEDULED("SCHEDULED"),
	SCHEDULED_ITEMS("SCHEDULED ITEMS"),
	SCULPTURES("SCULPTURES"),
	SECRET("sssshhhh!"),
	SELECT("SELECT"),
	SERIAL_NUMBER("Sr.No."),
	SETTLED("SETTLED"),
	SHA_256("SHA-256"),
	SOLITARE("SOLITARE"),
	SPACE(" "),
	SQUARE_CLOSE("]"),
	SQUARE_OPEN("["),	
	STAR("*"),
	STUD("STUD"),
	SUB("sub"),
	SUBCATEGORY("Sub-Category"),
	TABLET("tablet"),
	TASK("TASK"),
	TIMEZONE_UTC("UTC"),
	TOKEN_HEADER("X-Auth-Token"),
	TOTAL_COST("Total Cost"),
	TRUE("TRUE"),
	UNDER_REVIEW("UNDER REVIEW"),
	UNDERSCORE("_"),
	USER("USER"),
	USER_AGENT("ExampleBot 1.0 (+http://example.com/bot)"),
	UTF_8("UTF-8"),
	VENDOR("VENDOR"),
	VICINITY("vicinity"),
	WEB("web"),
	WEBAPPS("webapps"),
	WEIGHT_UNITS("weightunits"),
	WINE("WINE"),
	WINE_TYPE_AND_COLOR("winetypeandcolor"),
	WORK("WORK"),
	//YYYY_MM_DD("yyyy-MM-dd"),
	//YYYY_MM_DD_HH_MM_SS("yyyy-MM-dd HH:mm:ss"),
	YYYY_MM_DD_HH_MM_SS_WITHZONE("yyyy-MM-dd'T'HH:mm:ss'Z'"),
	ZERO("0"),
	ZERO_CHARACTER("'0'");
	
	private String value;

	BaseAppConstants(String value) {
		this.value = value;

	}

	public String getValue() {
		return value;
	}

}
