package com.nextgen.model;
// Generated Jan 4, 2017 7:28:37 PM by Hibernate Tools 4.3.1.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Contact generated by hbm2java
 */
@Entity
@Table(name = "employee", uniqueConstraints = @UniqueConstraint(columnNames = "USERNAME"))
public class Employee implements java.io.Serializable {

	private static final long serialVersionUID = -5377873949674092983L;
	private Long id;
	private String firstname;
	private String middlename;
	private String lastname;
	private String phone;
	private String email;
	private String password;
	private Date dob;
	private String authorities;
	private String gender;
	private Date hiredate;
	private String nationalId;
	private String addressLineOne;
	private String addressLineTwo;
	private String city;
	private String country;
	private String zip;
	private String state;
	private Date lastLogin;
	private String secretKey;
	private Date secretKeyExpiry;

	public Employee() {
		super();
	}

	public Employee(Long id, String firstname, String middlename, String lastname, String phone, String email,
			String password, Date dob, String authorities, String gender, Date hiredate, String nationalId,
			String addressLineOne, String addressLineTwo, String city, String country, String zip, String state,
			Date lastLogin, String secretKey, Date secretKeyExpiry) {
		super();
		this.id = id;
		this.firstname = firstname;
		this.middlename = middlename;
		this.lastname = lastname;
		this.phone = phone;
		this.email = email;
		this.password = password;
		this.dob = dob;
		this.authorities = authorities;
		this.gender = gender;
		this.hiredate = hiredate;
		this.nationalId = nationalId;
		this.addressLineOne = addressLineOne;
		this.addressLineTwo = addressLineTwo;
		this.city = city;
		this.country = country;
		this.zip = zip;
		this.state = state;
		this.lastLogin = lastLogin;
		this.secretKey = secretKey;
		this.secretKeyExpiry = secretKeyExpiry;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ID", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "FIRSTNAME")
	public String getFirstname() {
		return this.firstname;
	}

	public void setFirstname(String firstname) {
		this.firstname = firstname;
	}

	@Column(name = "LASTNAME")
	public String getLastname() {
		return this.lastname;
	}

	public void setLastname(String lastname) {
		this.lastname = lastname;
	}

	@Column(name = "USERNAME", unique = true, length = 45)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "PASSWORD")
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DOB", length = 19)
	public Date getDob() {
		return this.dob;
	}

	public void setDob(Date dob) {
		this.dob = dob;
	}

	@Column(name = "AUTHORITIES")
	public String getAuthorities() {
		return this.authorities;
	}

	public void setAuthorities(String authorities) {
		this.authorities = authorities;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LAST_LOGIN", length = 19)
	public Date getLastLogin() {
		return this.lastLogin;
	}

	public void setLastLogin(Date lastLogin) {
		this.lastLogin = lastLogin;
	}

	@Column(name = "SECRET_KEY")
	public String getSecretKey() {
		return this.secretKey;
	}

	public void setSecretKey(String secretKey) {
		this.secretKey = secretKey;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "SECRET_KEY_EXPIRY", length = 19)
	public Date getSecretKeyExpiry() {
		return this.secretKeyExpiry;
	}

	public void setSecretKeyExpiry(Date secretKeyExpiry) {
		this.secretKeyExpiry = secretKeyExpiry;
	}

	/**
	 * @return the middlename
	 */
	@Column(name = "MIDDILE_NAME")
	public String getMiddlename() {
		return middlename;
	}

	/**
	 * @return the phone
	 */
	@Column(name = "PHONE")
	public String getPhone() {
		return phone;
	}

	/**
	 * @return the gender
	 */
	@Column(name = "GENDER")
	public String getGender() {
		return gender;
	}

	/**
	 * @return the hiredate
	 */
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "HIRE_DATE", length = 19)
	public Date getHiredate() {
		return hiredate;
	}

	/**
	 * @return the nationalId
	 */
	@Column(name = "NATIONAL_ID")
	public String getNationalId() {
		return nationalId;
	}

	/**
	 * @return the addressLineOne
	 */
	@Column(name = "STREET_ADDRESS_LINE")
	public String getAddressLineOne() {
		return addressLineOne;
	}

	/**
	 * @return the addressLineTwo
	 */
	@Column(name = "ADDRESS_LINE")
	public String getAddressLineTwo() {
		return addressLineTwo;
	}

	/**
	 * @return the city
	 */
	@Column(name = "CITY")
	public String getCity() {
		return city;
	}

	/**
	 * @return the country
	 */
	@Column(name = "COUNTRY")
	public String getCountry() {
		return country;
	}

	/**
	 * @return the zip
	 */
	@Column(name = "ZIP")
	public String getZip() {
		return zip;
	}

	/**
	 * @return the state
	 */
	@Column(name = "STATE")
	public String getState() {
		return state;
	}

	/**
	 * @param middlename
	 *            the middlename to set
	 */
	public void setMiddlename(String middlename) {
		this.middlename = middlename;
	}

	/**
	 * @param phone
	 *            the phone to set
	 */
	public void setPhone(String phone) {
		this.phone = phone;
	}

	/**
	 * @param gender
	 *            the gender to set
	 */
	public void setGender(String gender) {
		this.gender = gender;
	}

	/**
	 * @param hiredate
	 *            the hiredate to set
	 */
	public void setHiredate(Date hiredate) {
		this.hiredate = hiredate;
	}

	/**
	 * @param nationalId
	 *            the nationalId to set
	 */
	public void setNationalId(String nationalId) {
		this.nationalId = nationalId;
	}

	/**
	 * @param addressLineOne
	 *            the addressLineOne to set
	 */
	public void setAddressLineOne(String addressLineOne) {
		this.addressLineOne = addressLineOne;
	}

	/**
	 * @param addressLineTwo
	 *            the addressLineTwo to set
	 */
	public void setAddressLineTwo(String addressLineTwo) {
		this.addressLineTwo = addressLineTwo;
	}

	/**
	 * @param city
	 *            the city to set
	 */
	public void setCity(String city) {
		this.city = city;
	}

	/**
	 * @param country
	 *            the country to set
	 */
	public void setCountry(String country) {
		this.country = country;
	}

	/**
	 * @param zip
	 *            the zip to set
	 */
	public void setZip(String zip) {
		this.zip = zip;
	}

	/**
	 * @param state
	 *            the state to set
	 */
	public void setState(String state) {
		this.state = state;
	}

}
